# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2021-03-04 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0042_auto_20210304_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mockmodel',
            name='user',
        ),
    ]
